src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GameRepository::class)
 */
class Game
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $logo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $background_image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duration;

    /**
     * @ORM\ManyToOne(targetEntity=Developer::class, inversedBy="games")
     * @ORM\JoinColumn(nullable=true)
     */
    private $developer;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getBackgroundImage(): ?string
    {
        return $this->background_image;
    }

    public function setBackgroundImage(?string $background_image): self
    {
        $this->background_image = $background_image;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): self
    {
        $this->duration = $duration;
        return $this;
    }

    public function getDeveloper(): ?Developer
    {
        return $this->developer;
    }

    public function setDeveloper(?Developer $developer): self
    {
        $this->developer = $developer;

        return $this;
    }
}

src/Controller/GameCrudController.php
<?php

namespace App\Controller;

use App\Entity\Game;
use App\Form\GameType;
use App\Repository\GameRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/game/crud")
 */
class GameCrudController extends AbstractController
{
    /**
     * @Route("/", name="game_crud_index", methods={"GET"})
     */
    public function index(GameRepository $gameRepository): Response
    {
        return $this->render('game_crud/index.html.twig', [
            'games' => $gameRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="game_crud_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $game = new Game();
        $form = $this->createForm(GameType::class, $game);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($game);
            $entityManager->flush();

            return $this->redirectToRoute('game_crud_index');
        }

        return $this->render('game_crud/new.html.twig', [
            'game' => $game,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="game_crud_show", methods={"GET"})
     */
    public function show(Game $game): Response
    {
        return $this->render('game_crud/show.html.twig', [
            'game' => $game,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="game_crud_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Game $game): Response
    {
        $form = $this->createForm(GameType::class, $game);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('game_crud_index');
        }

        return $this->render('game_crud/edit.html.twig', [
            'game' => $game,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="game_crud_delete", methods={"POST"})
     */
    public function delete(Request $request, Game $game): Response
    {
        if ($this->isCsrfTokenValid('delete'.$game->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($game);
            $entityManager->flush();
        }

        return $this->redirectToRoute('game_crud_index');
    }
}

templates/game_crud/_delete_form.html.twig
<form method="post" action="{{ path('game_crud_delete', {'id': game.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ game.id) }}">
    <button class="btn">Delete</button>
</form>

templates/game_crud/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/game_crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Game{% endblock %}

{% block body %}
    <h1>Edit Game</h1>

    {{ include('game_crud/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('game_crud_index') }}">back to list</a>

    {{ include('game_crud/_delete_form.html.twig') }}
{% endblock %}

templates/game_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Game index{% endblock %}

{% block body %}
    <h1>Game index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Logo</th>
                <th>Background_image</th>
                <th>Duration</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for game in games %}
            <tr>
                <td>{{ game.id }}</td>
                <td>{{ game.name }}</td>
                <td>{{ game.logo }}</td>
                <td>{{ game.backgroundImage }}</td>
                <td>{{ game.duration }}</td>
                <td>
                    <a href="{{ path('game_crud_show', {'id': game.id}) }}">show</a>
                    <a href="{{ path('game_crud_edit', {'id': game.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('game_crud_new') }}">Create new</a>
{% endblock %}

templates/game_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Game{% endblock %}

{% block body %}
    <h1>Create new Game</h1>

    {{ include('game_crud/_form.html.twig') }}

    <a href="{{ path('game_crud_index') }}">back to list</a>
{% endblock %}

templates/game_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Game{% endblock %}

{% block body %}
    <h1>Game</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ game.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ game.name }}</td>
            </tr>
            <tr>
                <th>Logo</th>
                <td>{{ game.logo }}</td>
            </tr>
            <tr>
                <th>Background_image</th>
                <td>{{ game.backgroundImage }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ game.duration }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('game_crud_index') }}">back to list</a>

    <a href="{{ path('game_crud_edit', {'id': game.id}) }}">edit</a>

    {{ include('game_crud/_delete_form.html.twig') }}
{% endblock %}